### ISSUE TITLE
RuntimeError: out of memory when batch size is bigger than 2

### ISSUE THREAD

**Issue by HYPJUDY** [yjxiong/action-detection#26]
Hi, when I train SSN on thumos14 with the command:
`python ssn_train.py thumos14 MODALITY -b 16 --lr_steps 20 40 --epochs 45`
, more specifically, `sudo python3 ssn_train.py thumos14 RGB -b 16 --lr_steps 20 40 --epochs 45`,
I got the `RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58` error.
Only when I reduced the batch size to 2 the error disappeared. The memory usage is 9256MiB/12207MiB 
 of one GPU when batch size is 2. But I quickly got nan loss most of the time. I didn't modify the release code except some small changes of name and path. So I think it's unreasonable that the batch size is so small. Does anyone know why?

My environment info is as follows,
Python3.5, Cuda 7.5, nvidia-smi:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.90                 Driver Version: 384.90                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 00000000:04:00.0 Off |                  N/A |
| 22%   58C    P2    72W / 250W |    325MiB / 12207MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  Off  | 00000000:05:00.0 Off |                  N/A |
| 26%   40C    P8    13W / 250W |     11MiB /  6081MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
```
I installed PyTorch by the following commands:
```
pip3 install http://download.pytorch.org/whl/cu75/torch-0.3.0.post4-cp35-cp35m-linux_x86_64.whl 
pip3 install torchvision
```

The full log is as follows.
``` bash
administrator@xxxx:xxxx/action-detection$ sudo python3 ssn_train.py thumos14 RGB -b 16 --lr_steps 20 40 --epochs 45

    Initializing SSN with base model: BNInception.
    SSN Configurations:
        input_modality:     RGB
        starting_segments:  2
        course_segments:    5
        ending_segments:    2
        num_segments:       9
        new_length:         1
        dropout_ratio:      0.8
        loc. regression:    ON
        bn_mode:            frozen

        stpp_configs:       (1, 1, 1)

/home/administrator/.local/lib/python3.5/site-packages/torch/nn/modules/module.py:482: UserWarning: src is not broadcastable to dst, but they have the same number of elements.  Falling back to deprecated pointwise behavior.
  own_state[name].copy_(param)
Freezing all BatchNorm2D layers
computing regression target normalizing constants


            SSNDataset: Proposal file data/thumos14_tag_val_proposal_list.txt parsed.

            There are 28231 usable proposals from 200 videos.
            6676 foreground proposals
            17950 incomplete_proposals
            3605 background_proposals

            Sampling config:
            FG/BG/INC: 1/1/6
            Video Centric: True

            Epoch size multiplier: 10

            Regression Stats:
            Location: mean -0.02322 std 0.08391
            Duration: mean -0.00504 std 0.19560

/usr/local/lib/python3.5/dist-packages/torchvision/transforms/transforms.py:156: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
  "please use transforms.Resize instead.")


            SSNDataset: Proposal file data/thumos14_tag_test_proposal_list.txt parsed.

            There are 33634 usable proposals from 210 videos.
            7298 foreground proposals
            21316 incomplete_proposals
            5020 background_proposals

            Sampling config:
            FG/BG/INC: 1/1/6
            Video Centric: True

            Epoch size multiplier: 1

            Regression Stats:
            Location: mean -0.02322 std 0.08391
            Duration: mean -0.00504 std 0.19560

group: first_conv_weight has 1 params, lr_mult: 1, decay_mult: 1
group: first_conv_bias has 1 params, lr_mult: 2, decay_mult: 0
group: normal_weight has 71 params, lr_mult: 1, decay_mult: 1
group: normal_bias has 71 params, lr_mult: 2, decay_mult: 0
group: BN scale/shift has 0 params, lr_mult: 1, decay_mult: 0
THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCStorage.cu line=58 error=2 : out of memory
inception_3a_1x1_bn torch.Size([576, 64, 28, 28])
inception_3a_3x3_bn torch.Size([576, 64, 28, 28])
inception_3a_double_3x3_2_bn torch.Size([576, 96, 28, 28])
inception_3a_pool_proj_bn torch.Size([576, 32, 28, 28])
Traceback (most recent call last):
  File "ssn_train.py", line 418, in <module>
    main()
  File "ssn_train.py", line 154, in main
    train(train_loader, model, activity_criterion, completeness_criterion, regression_criterion, optimizer, epoch)
  File "ssn_train.py", line 208, in train
    reg_target_var, prop_type_var)
  File "/home/administrator/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/administrator/.local/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 68, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/administrator/.local/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 78, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/administrator/.local/lib/python3.5/site-packages/torch/nn/parallel/parallel_apply.py", line 67, in parallel_apply
    raise output
  File "/home/administrator/.local/lib/python3.5/site-packages/torch/nn/parallel/parallel_apply.py", line 42, in _worker
    output = module(*input, **kwargs)
  File "/home/administrator/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/share/v-yuphu/action-detection/ssn_models.py", line 255, in forward
    return self.train_forward(input, aug_scaling, target, reg_target, prop_type)
  File "/mnt/share/v-yuphu/action-detection/ssn_models.py", line 266, in train_forward
    base_out = self.base_model(input.view((-1, sample_len) + input.size()[-2:]))
  File "/home/administrator/.local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/share/v-yuphu/action-detection/model_zoo/bninception/pytorch_load.py", line 56, in forward
    data_dict[op[2]] = torch.cat(tuple(data_dict[x] for x in op[-1]), 1)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
THCudaCheckWarn FAIL file=/pytorch/torch/lib/THC/THCStream.cpp line=50 error=29 : driver shutting down
THCudaCheckWarn FAIL file=/pytorch/torch/lib/THC/THCStream.cpp line=50 error=29 : driver shutting down

```

**Comment by HYPJUDY** [comment]
When batch size is 2, sometimes I quickly got nan loss but sometimes I could train and got worse results as follows.
training command: `python3 ssn_train.py thumos14 RGB -b 2 --lr_steps 20 40 --epochs 45`
evaluation results:
```
+Detection Performance on thumos14------+--------+--------+--------+--------+--------+--------+---------+
| IoU thresh | 0.10   | 0.20   | 0.30   | 0.40   | 0.50   | 0.60   | 0.70   | 0.80   | 0.90   | Average |
+------------+--------+--------+--------+--------+--------+--------+--------+--------+--------+---------+
| mean AP    | 0.2434 | 0.2041 | 0.1652 | 0.1188 | 0.0786 | 0.0451 | 0.0232 | 0.0100 | 0.0030 | 0.0990  |
+------------+--------+--------+--------+--------+--------+--------+--------+--------+--------+---------+
```

Is it because that the authors used 8 gpus and each gpu is assigned batch_size = 2 (16/8) ?

**Comment by cc786537662** [comment]
@HYPJUDY hello, I have the same question as yours(both bastchsize and nan loss ),and i can also  only train when -b 2 ，otherwise  out of memory occurs，and also the evaluation results is much worse than the author reported.

**Comment by bityangke** [comment]
@cc786537662 @HYPJUDY Did you try the trained model by the authors?

**Comment by cc786537662** [comment]
@bityangke yes,only run the sst_test.py and the eval_detection_results.py works fine with me,and the result is the same as the author says,but after use the train code and the test MAP goes down heavily

**Comment by yjxiong** [comment]
The batchsize 16 is tested on 8 GPUs. If you only have 1 GPU, you should use `-b 2 -i 8` to have an effective batchsize of 16. Otherwise, the training will be unstable and iteration will be insufficient for convergence.

**Comment by HYPJUDY** [comment]
@yjxiong Thanks! I will try. I have two GPUs, one is 12G and the other is 6G memory. It seems that I can only use `-b 2` as one 12G GPU.

**Comment by bityangke** [comment]
@HYPJUDY Aren’t you an internship in msra, why so few graphics cards？

**Comment by HYPJUDY** [comment]
Hi @bityangke , you can see #27. @cc786537662 could you help me with #27 ?

**Comment by HYPJUDY** [comment]
I got bad results when I only modify `-b 16` to `-b 2 -i 8`. It seems that the learning rate, learning policy, epoch and some other parameters should also be modified. Can you give me some suggestions on it? I am afraid that I miss something and waste too much time training. @yjxiong @bityangke @cc786537662

**Comment by HYPJUDY** [comment]
Train with command: `python ssn_train.py thumos14 RGB -b 2 -i 8 --lr_steps 160 320 --epochs 360`
I got evaluation result:
```
+Detection Performance on thumos14------+--------+--------+--------+--------+--------+--------+---------+
| IoU thresh | 0.10   | 0.20   | 0.30   | 0.40   | 0.50   | 0.60   | 0.70   | 0.80   | 0.90   | Average |
+------------+--------+--------+--------+--------+--------+--------+--------+--------+--------+---------+
| mean AP    | 0.4354 | 0.3899 | 0.3340 | 0.2542 | 0.1863 | 0.1146 | 0.0665 | 0.0282 | 0.0052 | 0.2016  |
+------------+--------+--------+--------+--------+--------+--------+--------+--------+--------+---------+
```
Compare with evaluation by reference model:
```
+Detection Performance on thumos14------+--------+--------+--------+--------+--------+--------+---------+
| IoU thresh | 0.10   | 0.20   | 0.30   | 0.40   | 0.50   | 0.60   | 0.70   | 0.80   | 0.90   | Average |
+------------+--------+--------+--------+--------+--------+--------+--------+--------+--------+---------+
| mean AP    | 0.4512 | 0.4036 | 0.3450 | 0.2560 | 0.1820 | 0.1132 | 0.0660 | 0.0261 | 0.0060 | 0.2054  |
+------------+--------+--------+--------+--------+--------+--------+--------+--------+--------+---------+
```

**Comment by yjxiong** [comment]
The results look ok. Do you have other problem?

**Comment by HYPJUDY** [comment]
Thanks for your help!

**Comment by bityangke** [comment]
@HYPJUDY  It seems each "epoch"  here have fixed iter numbers，so you need to train your model with more epoch numbers (about 8x).

**Comment by kstys** [comment]
hello,
thank you for your attention.
I come cross a trouble that I can't solve it.so(I am a green hand using pytorch) ,I hope your help,thanks a lot.

when i load the module parameter ,and it will say:
RuntimeError: While copying the parameter named inception_5a_3x3_reduce_bn.running_mean, whose dimensions in the model are torch.Size([192]) and whose dimensions in the checkpoint are torch.Size([1, 192]).
and then I want to modify the model to adapt it ,but how to do it ? or you have the other method to do with it??
@HYPJUDY @cc786537662 @bityangke
